"""   To Parse the JSON generated by driver   """
import json

class Parser:
    '''   Properties to store parsed data   '''
    request_type: str = ''
    meta_data: dict = {}
    user_data: dict = {}

    # Method to parse JSON string.
    def parse(self, raw_data: str):
        raw_data = json.loads(raw_data)
        self.request_type = list(raw_data.keys())[0]
        self.meta_data = raw_data[list(raw_data.keys())[0]]["meta"]
        self.user_data = raw_data[list(raw_data.keys())[0]]["data"]
    
    # Method to get Resquest Type
    def getRequestType(self):
        return self.request_type

    # Method to get Meta Data
    def getMetaData(self):
        return self.meta_data

    # Method to get User Data
    def getUserData(self):
        return self.user_data
